export const SET_FILM = "SET_FILM";
export const SET_FILM_DETAIL = "SET_FILM_DETAIL";
export const SET_CHI_TIET_PHONG_VE = "SET_CHI_TIET_PHONG_VE"
export const DAT_GHE = "DAT_GHE"
export const XOA_DANH_SACH_GHE_DANG_DAT = "XOA_DANH_SACH_GHE_DANG_DAT"
export const SEARCH_FILM = "SEARCH_FILM"
export const GET_HE_THONG_RAP = "GET_HE_THONG_RAP"